### PR TITLE
pcornet_mapping: include med curation (#4585)

### PR DESCRIPTION
**Pull request by dckc**

### CODE REVIEW

**Review by njgraham — COMMENTED** [review]
It seems like there are more than one topics mixed in with this pull request (labs and meds).  I wonder if these changes address items that show up in the EDC report.  If so, I'm tempted to say that if we have run the code and the EDC report shows the expected improvement in these areas we go ahead and merge.

**Comment by dckc** [comment]
I mixed up the branch I want to merge into; hang on...

**Comment by dckc** [comment]
"There are no new commits between base branch 'cycle_2_refresh_2' and head branch 'med_curate' "

I guess this has already been merged as a consequence of another PR.

**Comment by dckc** [comment]
I changed the default branch here in github to `cycle_2_refresh_2` a little while ago, but to further reduce risk of confusion, I just merged `cycle_2_refresh_2` into `master`, since we're using it in production.

**Pull request closed without merging**
