### PR TITLE
Logging 4713

### PR DESCRIPTION
**Pull request by mprittie**

### CODE REVIEW

**Comment by dckc** [comment]
can't tell where PR #85 end and this one starts yet. I'll take a look after we finish talking about #85.

**Comment by mprittie** [comment]
[Comparision of the two](https://github.com/kumc-bmi/i2p-transform/compare/breakup_sql_4714...kumc-bmi:logging_4713).

**Review by dckc — APPROVED** [review]
Looks good, based on the comparison with the `breakup_sql_4714` PR (i.e.  	89aba65 thru  	76d9be6).

It seems a little odd that indexing changes and SQL unrelated SQL syntax fixes went into this PR, but no matter.

I'm not confident how a merge would work with #85 outstanding, so I'm holding off for now.

**Comment by mprittie** [comment]
Due to a lack of discipline on my part, this branch includes thing it probably shouldn't.  Sorry if that muddies things up.

**Pull request merged**
